### ISSUE TITLE
Poster upload link 404

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2024#11]
@tyrasd https://2024.stateofthemap.org/calls/posters/ is broken.
in fact the 2022 page has simply covered over the 2024 page.

I recommend:
1. Not having strings like xKeT6JRap embedded into this webpage. Instead just  have ../posters/upload and keep the rest of the details under the hood.
2. Have an email sent: "Thank you for your poster, abc.pdf, 334 Kb." Else the user cannot be sure OSM really did get the poster, as staff doesn't look at the SOTM mailbox every day.

**Comment by jidanni** [comment]
Wait. Somebody simply has copied the 2022 page into
https://2024.stateofthemap.org/calls/posters/
So someone needs to find the 2024 page and put it back.

**Comment by tyrasd** [comment]
Thx, fixed.

**Comment by jidanni** [comment]
Thanks. Also I wish the staff would send a hand typed email to each submitter, saying that they indeed received their file. Else next thing you know the Deadline will have already passed, and some people thought staff received their files, but that is/was not the case. Note I am talking about files submitted weeks ago, in addition to files submitted weeks from now.
