### ISSUE TITLE
ical support for schedule

### ISSUE THREAD

**Issue by bkmgit** [openstreetmap/stateofthemap-2024#16]
Would you consider a pull request to add ical support to the schedule?  This would add a dependency on the [icalender gem](https://rubygems.org/gems/icalendar)?  This would be helpful for people who want to import the schedule into their calender applications.

**Comment by tyrasd** [comment]
@zverik do you plan on releasing the ical (and giggity) files on https://sotm.osmz.ru/ this year again?

**Comment by Zverik** [comment]
Sure!

**Comment by Zverik** [comment]
@bkmgit see the ical here: https://sotm.osmz.ru/sotm2024.html

**Comment by Zverik** [comment]
Giggity PR done: https://github.com/Wilm0r/giggity/pull/372

**Comment by tyrasd** [comment]
Great. It seems like the academic track talks (https://pretalx.com/state-of-the-map-2024-academic-track/schedule/) in Tsavo Hall on Sunday are still missing in the ICS and giggity, can you add those if possible?

**Comment by tyrasd** [comment]
I've added links to the ICS file and giggity to the website programme page in 520f072

**Comment by bkmgit** [comment]
@tyrasd @Zverik Thanks.

**Comment by Zverik** [comment]
@tyrasd Added the academic track, thanks for pointing that out :)
