### ISSUE TITLE
Conference room locations

### ISSUE THREAD

**Issue by bkmgit** [openstreetmap/stateofthemap-2024#18]
University of Nairobi Towers does not have rooms named Tsavo Hall, Amboselli Hall and Maasai Mara. There is a [Tsavo Hall](https://kicc.co.ke/tsavo-hall/) at [KICC](https://kicc.co.ke) but probably the room names are specific to the event.  Is it possible to add the regular room names? This would enable creating preliminary indoor maps before the event and also easier direction on initial arrival.

**Comment by tyrasd** [comment]
>  room names are specific to the event.

Yes, these names are specific for the State of the Map. Below is the correspondence to the official room names:

SotM room name | Official Name
-- | --
Maasai Mara | Chandaria Auditorium
Amboseli Hall | MLT 403
Aberdare Hall | MLT 404
Tsavo Hall | MLT 405

**Comment by bkmgit** [comment]
Thanks.
