### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2024#24]
https://2024.stateofthemap.org/stream/ has broken links, starting here:
> If you prefer watching the live stream using a dedicated player instead of the embedded one on this page, you can use the following URLs:

**Comment by jidanni** [comment]
By the way, many users might not have bought tickets if they knew free streams would be available. So be sure to mention it next year.

**Comment by tyrasd** [comment]
The links for the dedicated players work for me (try them in VLC -> Open Network Stream…).

> so be sure to mention it next year.

Yeah, next year we might have to communicate this a bit better.

**Comment by jidanni** [comment]
Today it only worked for an hour, then this:
![Screenshot 2024-09-08 15 14 01](https://github.com/user-attachments/assets/e614659f-4bc2-4dc7-9810-132291a569bb)
Wait, now it is working again.

**Comment by tyrasd** [comment]
There was a short hiccup in the stream from Tsavo Hall earlier. It should work now again.

**Comment by jidanni** [comment]
Well it still pauses every 20 seconds, for two seconds. Even with audio-only. Must be a Kenyan bandwidth problem.

**Comment by jidanni** [comment]
As far as venueless.* , today it is just a white screen for me.
![Screenshot 2024-09-08 16 14 02](https://github.com/user-attachments/assets/298712f2-43ea-4f76-999a-62f1a1c9f114)
Wait, now it is working again.

How about instead of a white screen, a message could be shown next time. Maybe you could tell that company my suggestion.
