### ISSUE TITLE
mailto link causes trailing '>'

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2024#5]
On https://blog.openstreetmap.org/2024/03/20/sotm-2024-call-for-participation/
it says
> email (program-sotm@openstreetmap.org>)

I.e., a trailing `>` is seen due to garbled interpretation of HTML mailto link in Markdown, apparently.

**Comment by tyrasd** [comment]
I think the brackets were put on purpose to make the email address stand out visually. But on that line, the opening bracket is apparently missing.

@enockseth :point_up_2: can you fix this small typo on the blog post, please?

**Comment by Firefishy** [comment]
I have fixed the typo in the post.
